### ISSUE TITLE
zacks-api not working

### ISSUE THREAD

**Issue by wuliwei9278** [janlukasschroeder/zacks-api#1]
It seems zacks-api not working any more. 

Error message is like this:
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/zacks-api/helpers.js:21:24)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by janlukasschroeder** [comment]
Is working now
